name: Deploy UI to EC2

on:
  push:
    branches:
      - main  # Trigger this workflow when code is pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.APP_EC2_HOST }}
        username: ${{ secrets.APP_EC2_USER }}
        key: ${{ secrets.APP_EC2_SSH_KEY }}
        script: |
          cd ~/nextjs-ollama-llm-ui
          ./deploy.sh
